{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  {{- include "ui.lables" . | nindent 4 }} 
spec:
  maxReplicas: {{ .Values.hpa.maxreplicas }}
  minReplicas: {{ .Values.hpa.minreplicas }}
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: react-ui-deploy
  targetCPUUtilizationPercentage: {{ .Values.hpa.cuputi }}
{{- end -}}