apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sevice.name }}
  labels:
  {{- include "ui.labels" . | nindent 4 }} 
spec:
  ports:
  - name: http
    port: {{ .Values.app.container.port }}
    targetPort: {{ .Values.app.container.port }}
  selector:
    app: react-ui
  type: NodePort