app:
  name: react-ui-deploy
  replicas: 1
  labels:
    app: react-ui
    env: dev
  container:
    image: deekshithsn/ui
    tag: latest
    name: react-ui
    port: 8080
    command: []
    args: []
  computerc:
    limits:
      cpu: 0.2
      memory: 500Mi
    requests:
      cpu: 0.2
      memory: 500Mi

sevice:
  name: ui-service
hpa:
  enabled: false